//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Basket()
        {
            this.OrderClient = new HashSet<OrderClient>();
        }
    
        public int id_Basket { get; set; }
        public int id_Medicament { get; set; }
        public string ficClient { get; set; }
        public int countMedicament { get; set; }
        public Nullable<int> id_Workers { get; set; }
        public Nullable<int> Id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Users Users { get; set; }
        public virtual Medicament Medicament { get; set; }
        public virtual Workers Workers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderClient> OrderClient { get; set; }
    }
}
