//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderClient
    {
        public int id_Order { get; set; }
        public Nullable<System.DateTime> dateOrder { get; set; }
        public int id_Basket { get; set; }
        public int id_Employee { get; set; }
    
        public virtual Basket Basket { get; set; }
    }
}
