//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public int id_MedicamentPosition { get; set; }
        public int id_Medicament { get; set; }
        public int countOnStorage { get; set; }
    
        public virtual Medicament Medicament { get; set; }
    }
}
